CREATE DATABASE QLGV
USE QLGV

CREATE TABLE GIAOVIEN
( 
	MAGV char(4),
	HOTEN varchar(40),
	HOCVI varchar(10),
	HOCHAM varchar(10),
	NGSINH smalldatetime,
	NGVL smalldatetime,
	HESO numeric(4,2),
	MUCLUONG money,
	MAKHOA varchar(4),
	PRIMARY KEY (MAGV),
	--FOREIGN KEY (MAKHOA) REFERENCES KHOA(MAKHOA)
)
ALTER TABLE GIAOVIEN

CREATE TABLE KHOA
(
	MAKHOA varchar(4) NOT NULL,
	TENKHOA varchar(40),
	NGTLAP smalldatetime,
	TRGKHOA char(4),
	PRIMARY KEY (MAKHOA),
)


CREATE TABLE LOP 
(
	MALOP char(3) NOT NULL,
	TENLOP varchar(40),
	TRGLOP char(5),
	SISO tinyint,
	MAGVCN char(4),
	PRIMARY KEY (MALOP),
	FOREIGN KEY (MAGVCN) REFERENCES GIAOVIEN(MAGV)
)

CREATE TABLE HOCVIEN
(
	MAMH char(5) NOT NULL,
	TEN varchar (40),
	NGSINH smalldatetime,
	GIOITINH varchar(3),
	NOISINH	varchar(40),
	MALOP char(3),
	PRIMARY KEY (MAMH),
	FOREIGN KEY (MALOP) REFERENCES LOP (MALOP)
)




CREATE TABLE MONHOC
(
	MAMH varchar(10) NOT NULL,
	TENMH varchar(40),
	TCLT tinyint,
	TCTH tinyint,
	MAKHOA varchar(4),
	PRIMARY KEY (MAMH),
	FOREIGN KEY (MAKHOA) REFERENCES KHOA(MAKHOA)
)

CREATE TABLE DIEUKIEN
(
	MAMH varchar(10),
	MAMH_TRUOC varchar(10),
	PRIMARY KEY (MAMH, MAMH_TRUOC),
	FOREIGN KEY (MAMH) REFERENCES MONHOC(MAMH)
)